### ISSUE TITLE
Autocompleting .eslintrc.json

### ISSUE THREAD

**Issue by petermbenjamin** [bali182/autocomplete-json#62] opened 2017-03-14 05:58 UTC
The plugin doesn't seem to autocomplete `.eslintrc.json` files for me, even when pressing <kbd>CTRL</kbd> + <kbd>SPACE</kbd>

I verified that `.eslintrc.json` exists in [http://schemastore.org/api/json/catalog.json](http://schemastore.org/api/json/catalog.json):
  ```
  {
    "name": ".eslintrc",
    "description": "JSON schema for ESLint configuration files",
    "fileMatch": [
        ".eslintrc",
        ".eslintrc.json"
    ],
    "url": "http://json.schemastore.org/eslintrc"
  },
  ```

Steps to reproduce:
- Generate `.eslintrc.json` via `$ eslint --init`
- Open `.eslintrc.json` and press <kbd>CTRL</kbd> + <kbd>SPACE</kbd>, nothing happens.

**Comment by bali182** [comment] 2017-03-14 18:54
Hey Peter, and thanks for reporting this! 

I think your problem might be related to #56. The basic issue is that autocomplete+ (this package is a plugin for autocomplete+) blacklists dotfiles for some reason by default, and to enable any kind of autocomplete for them you have to go to File -> Settings -> Packages -> autocomplete-plus -> Settings -> override default .* with something else that you don't expect as a file name pattern - a space for example. 

Let me know if it helps! 

Once I have the time I will update the readme, because I suspect you are not the last person who will have this issue.

**Comment by bali182** [comment] 2017-03-14 18:58
I opened an issue a while back in the ac+ repo, but it seems like they intended it to work this way 

https://github.com/atom/autocomplete-plus/issues/658

**Comment by bali182** [comment] 2017-03-16 11:22
Closing this, let me know if the problem persists!

**Comment by petermbenjamin** [comment] 2017-03-16 18:29
1. Went to `File` -> `Settings` -> `Packages` -> `autocomplete-plus` -> `Settings` -> `File Blacklist`
2. Changed the default `.*` value to ` ` (space).
### autocomplete-plus Settings:
<img width="785" alt="screen shot 2017-03-16 at 11 22 42 am" src="https://cloud.githubusercontent.com/assets/6811830/24012562/b0ba0408-0a3b-11e7-9fcd-9223db0d1426.png">

### config.cson:
<img width="258" alt="screen shot 2017-03-16 at 11 22 23 am" src="https://cloud.githubusercontent.com/assets/6811830/24012568/b47cf398-0a3b-11e7-868b-447abf92d26c.png">


Still not able to get autocompletion in `.eslintrc.json`

**Comment by bali182** [comment] 2017-03-16 21:11
Ok, thanks for verifying, will try to repro!

**Comment by petermbenjamin** [comment] 2017-03-16 23:37
Atom: 1.15.0
Autocomplete-Plus: 2.34.2
Autocomplete-JSON: 5.3.0

**Comment by bali182** [comment] 2017-03-17 21:19
@petermbenjamin reproduced & fix is on the way :)

**Closed** 2017-03-18 23:18 UTC

**Comment by bali182** [comment] 2017-03-18 23:21
Should be working in v5.4.0! Thank you for reporting it!
